import { MONTH_NAMES } from './config.js';
import { $, normalizeDate, sameDay, renderMonthInto, isoWeekInfo } from './utils.js';

const cal = { track: null, curr: null, nextbuf: null, title: null, legend: null, toggle: null, prev: null, next: null, today: null, month: null, year: null, collapsed: false, focusDate: null, monthWeeks: [], activeWeekIndex: 0 };

function monthTitle(y, m) { return `${MONTH_NAMES[m]} ${y}`; }
function weekTitle(date) { const info = isoWeekInfo(date); return `Неделя ${String(info.week).padStart(2, '0')} · ${monthTitle(date.getFullYear(), date.getMonth())}`; }
function findWeekIndexForDate(weeks, date) { if (!date) return -1; for (let i = 0; i < weeks.length; i++) { if (weeks[i].days.some(cell => sameDay(cell.d, date))) return i; } return -1; }
function ensureFocusDateVisible(weeks) { if (!cal.focusDate) return; if (findWeekIndexForDate(weeks, cal.focusDate) !== -1) return; for (const week of weeks) { const inMonthDay = week.days.find(cell => cell.inMonth); if (inMonthDay) { cal.focusDate = normalizeDate(inMonthDay.d); return; } } }
function highlightWeeks() { if (!cal.curr) return; const weekEls = cal.curr.querySelectorAll('.cal-week'); weekEls.forEach((el, idx) => { el.classList.toggle('is-active', idx === cal.activeWeekIndex); }); }
function applyCollapsedState() { const root = document.getElementById('calendar'); if (!root) return; root.classList.toggle('is-collapsed', cal.collapsed); if (cal.legend) cal.legend.setAttribute('aria-hidden', cal.collapsed ? 'true' : 'false'); highlightWeeks(); if (cal.prev) { const prevLabel = cal.collapsed ? 'Предыдущая неделя' : 'Предыдущий месяц'; cal.prev.setAttribute('aria-label', prevLabel); cal.prev.title = prevLabel; } if (cal.next) { const nextLabel = cal.collapsed ? 'Следующая неделя' : 'Следующий месяц'; cal.next.setAttribute('aria-label', nextLabel); cal.next.title = nextLabel; } if (cal.today) { const todayLabel = cal.collapsed ? 'Текущая неделя' : 'Текущий месяц'; const todayTitle = cal.collapsed ? 'Перейти к текущей неделе' : 'Перейти к текущему месяцу'; cal.today.setAttribute('aria-label', todayLabel); cal.today.title = todayTitle; } if (cal.toggle) { const toggleLabel = cal.collapsed ? 'Развернуть календарь' : 'Свернуть календарь'; cal.toggle.setAttribute('aria-pressed', cal.collapsed ? 'true' : 'false'); cal.toggle.setAttribute('aria-label', toggleLabel); cal.toggle.title = toggleLabel; cal.toggle.textContent = cal.collapsed ? '▴' : '▾'; } }
function updateCalendarTitle() { if (!cal.title) return; const baseDate = cal.focusDate || new Date(cal.year || new Date().getFullYear(), cal.month || 0, 1); cal.title.textContent = cal.collapsed ? weekTitle(baseDate) : monthTitle(cal.year, cal.month); }
function setMonth(y, m, { animateDir = null, focusDate = null, keepFocus = false } = {}) { let targetFocus = focusDate ? normalizeDate(focusDate) : cal.focusDate; if ((!targetFocus || (targetFocus.getFullYear() !== y || targetFocus.getMonth() !== m)) && !keepFocus) { targetFocus = new Date(y, m, 1); targetFocus = normalizeDate(targetFocus); } cal.focusDate = targetFocus; if (animateDir && !cal.collapsed) { const weeks = renderMonthInto(cal.nextbuf, y, m, { minVisibleDays: 2, maxWeeks: 5 }); cal.track.style.transition = 'none'; cal.track.style.transform = animateDir > 0 ? 'translateX(0%)' : 'translateX(-100%)'; requestAnimationFrame(() => { requestAnimationFrame(() => { cal.track.style.transition = 'transform .24s ease'; cal.track.style.transform = animateDir > 0 ? 'translateX(-100%)' : 'translateX(0%)'; }); }); const onEnd = () => { cal.track.removeEventListener('transitionend', onEnd); cal.curr.innerHTML = cal.nextbuf.innerHTML; cal.track.style.transition = 'none'; cal.track.style.transform = 'translateX(0%)'; cal.year = y; cal.month = m; cal.monthWeeks = weeks; ensureFocusDateVisible(cal.monthWeeks); cal.activeWeekIndex = findWeekIndexForDate(cal.monthWeeks, cal.focusDate); if (cal.activeWeekIndex === -1) cal.activeWeekIndex = 0; applyCollapsedState(); updateCalendarTitle(); }; cal.track.addEventListener('transitionend', onEnd, { once: true }); } else { const weeks = renderMonthInto(cal.curr, y, m, { minVisibleDays: 2, maxWeeks: 5 }); cal.year = y; cal.month = m; cal.monthWeeks = weeks; ensureFocusDateVisible(cal.monthWeeks); cal.activeWeekIndex = findWeekIndexForDate(cal.monthWeeks, cal.focusDate); if (cal.activeWeekIndex === -1) cal.activeWeekIndex = 0; if (cal.track) { cal.track.style.transition = 'none'; cal.track.style.transform = 'translateX(0%)'; } applyCollapsedState(); updateCalendarTitle(); } }
function setFocusDate(date) { const normalized = normalizeDate(date); cal.focusDate = normalized; const fy = normalized.getFullYear(); const fm = normalized.getMonth(); if (fy !== cal.year || fm !== cal.month) { setMonth(fy, fm, { focusDate: normalized }); } else { ensureFocusDateVisible(cal.monthWeeks); cal.activeWeekIndex = findWeekIndexForDate(cal.monthWeeks, cal.focusDate); if (cal.activeWeekIndex === -1) cal.activeWeekIndex = 0; applyCollapsedState(); updateCalendarTitle(); } }
function shiftMonth(dir) { let y = cal.year, m = cal.month + dir; if (m < 0) { m = 11; y--; } else if (m > 11) { m = 0; y++; } setMonth(y, m, { animateDir: dir, focusDate: new Date(y, m, 1) }); }
function shiftWeek(dir) { if (!cal.focusDate) cal.focusDate = normalizeDate(new Date(cal.year, cal.month, 1)); const nextDate = new Date(cal.focusDate); nextDate.setDate(nextDate.getDate() + dir * 7); setFocusDate(nextDate); }
function jumpToToday() { const now = normalizeDate(new Date()); if (cal.collapsed) { setFocusDate(now); return; } const ty = now.getFullYear(); const tm = now.getMonth(); const dir = ty === cal.year && tm === cal.month ? null : (ty > cal.year || (ty === cal.year && tm > cal.month)) ? 1 : -1; setMonth(ty, tm, { animateDir: dir, focusDate: now }); }
function setCollapsed(state) { const nextState = !!state; if (cal.collapsed === nextState) return; cal.collapsed = nextState; if (!cal.focusDate) { cal.focusDate = normalizeDate(new Date(cal.year || new Date().getFullYear(), cal.month || 0, 1)); } if (!cal.collapsed) { const fy = cal.focusDate.getFullYear(); const fm = cal.focusDate.getMonth(); if (fy !== cal.year || fm !== cal.month) { setMonth(fy, fm, { focusDate: cal.focusDate }); return; } } applyCollapsedState(); updateCalendarTitle(); }

export function initCalendar() {
  cal.track = $('#calTrack'); cal.curr = $('#calCurr'); cal.nextbuf = $('#calNextBuf'); cal.title = $('#calTitle');
  cal.legend = document.querySelector('#calendar .cal-legend'); cal.toggle = $('#calToggle');
  cal.prev = $('#calPrev'); cal.next = $('#calNext'); cal.today = $('#calToday');
  const now = normalizeDate(new Date());
  cal.month = now.getMonth(); cal.year = now.getFullYear(); cal.focusDate = now;
  setMonth(cal.year, cal.month, { focusDate: now }); applyCollapsedState();
  if (cal.prev) cal.prev.addEventListener('click', () => { cal.collapsed ? shiftWeek(-1) : shiftMonth(-1); });
  if (cal.next) cal.next.addEventListener('click', () => { cal.collapsed ? shiftWeek(1) : shiftMonth(1); });
  if (cal.today) cal.today.addEventListener('click', () => jumpToToday());
  if (cal.toggle) cal.toggle.addEventListener('click', () => setCollapsed(!cal.collapsed));
}
