const _cb = {};
export function registerEffectsCallbacks(cbs) { Object.assign(_cb, cbs); }

const EffectsStore = { key: 'mini-task-tracker:effects', read() { try { return JSON.parse(localStorage.getItem(this.key)) || {} } catch { return {} } }, write(d) { try { localStorage.setItem(this.key, JSON.stringify(d)) } catch {} } };
const DEFAULT_EFFECTS_SETTINGS = { sound: true, confetti: true };
let effectsSettings = { ...DEFAULT_EFFECTS_SETTINGS, ...EffectsStore.read() };
function updateEffectsSetting(key, value) { if (!(key in DEFAULT_EFFECTS_SETTINGS)) return; const next = { ...effectsSettings, [key]: !!value }; effectsSettings = next; EffectsStore.write(next); }
function isSoundEnabled() { return effectsSettings.sound !== false; }
function isConfettiEnabled() { return effectsSettings.confetti !== false; }
if (typeof window !== 'undefined') { window.TaskEffectsSettings = { get: () => ({ ...effectsSettings }), set: (key, value) => updateEffectsSetting(key, value) }; }

const prefersReducedMotionQuery = typeof window !== 'undefined' && 'matchMedia' in window ? window.matchMedia('(prefers-reduced-motion: reduce)') : null;
export function isMotionReduced() { return !!(prefersReducedMotionQuery && prefersReducedMotionQuery.matches); }

let sessionCompletedCount = 0;
let audioCtx = null;
function ensureAudioContext() { if (typeof window === 'undefined' || typeof window.AudioContext === 'undefined') return null; if (!audioCtx) { audioCtx = new AudioContext(); } if (audioCtx.state === 'suspended') { try { audioCtx.resume(); } catch {} } return audioCtx; }
function playTaskCompleteBell(baseFreq) { const ctx = ensureAudioContext(); if (!ctx) return; const now = ctx.currentTime; const masterGain = ctx.createGain(); masterGain.gain.setValueAtTime(0.0001, now); masterGain.connect(ctx.destination); masterGain.gain.exponentialRampToValueAtTime(0.85, now + 0.01); masterGain.gain.exponentialRampToValueAtTime(0.0001, now + 1.6); const hits = [{ offset: 0, freq: baseFreq * 0.62, modFreq: 3.2, modDepth: 14, attack: 0.01, sustain: 0.16, decay: 1.2, peak: 0.7, type: 'sine' }, { offset: 0.08, freq: baseFreq * 0.94, modFreq: 7.5, modDepth: 20, attack: 0.008, sustain: 0.14, decay: 1, peak: 0.55, type: 'triangle' }, { offset: 0.18, freq: baseFreq * 1.36, modFreq: 11, modDepth: 12, attack: 0.006, sustain: 0.1, decay: 0.9, peak: 0.38, type: 'triangle' }]; for (const hit of hits) { const osc = ctx.createOscillator(); const mod = ctx.createOscillator(); const modGain = ctx.createGain(); const env = ctx.createGain(); osc.type = hit.type || 'sine'; osc.frequency.setValueAtTime(hit.freq, now + hit.offset); mod.type = 'sine'; mod.frequency.setValueAtTime(hit.modFreq, now + hit.offset); modGain.gain.setValueAtTime(hit.modDepth, now + hit.offset); mod.connect(modGain); modGain.connect(osc.frequency); const attackEnd = now + hit.offset + hit.attack; const sustainEnd = attackEnd + hit.sustain; const releaseEnd = sustainEnd + hit.decay; env.gain.setValueAtTime(0.0001, now + hit.offset); env.gain.exponentialRampToValueAtTime(Math.max(0.0001, hit.peak), attackEnd); env.gain.exponentialRampToValueAtTime(Math.max(0.0001, hit.peak * 0.6), sustainEnd); env.gain.exponentialRampToValueAtTime(0.0001, releaseEnd); osc.connect(env); env.connect(masterGain); osc.start(now + hit.offset); mod.start(now + hit.offset); const stopAt = now + hit.offset + Math.max(hit.attack + hit.sustain + hit.decay + 0.2, 0.5); osc.stop(stopAt); mod.stop(stopAt); } setTimeout(() => masterGain.disconnect(), 1700); }

const confettiState = new WeakMap();
function ensureTaskCanvas(row) { let canvas = row.querySelector('.task-confetti'); if (!canvas) { canvas = document.createElement('canvas'); canvas.className = 'task-confetti'; row.appendChild(canvas); } return canvas; }
function spawnTaskConfetti(rowEl, checkboxEl) { if (!rowEl || !checkboxEl) return; if (!isConfettiEnabled() || isMotionReduced()) return; const rect = rowEl.getBoundingClientRect(); if (!rect.width || !rect.height) return; const canvas = ensureTaskCanvas(rowEl); const ctx = canvas.getContext('2d'); if (!ctx) return; const dpr = window.devicePixelRatio || 1; const width = Math.round(rect.width * dpr); const height = Math.round(rect.height * dpr); if (canvas.width !== width || canvas.height !== height) { canvas.width = width; canvas.height = height; canvas.style.width = rect.width + 'px'; canvas.style.height = rect.height + 'px'; } const checkboxRect = checkboxEl.getBoundingClientRect(); const originX = (checkboxRect.left - rect.left + checkboxRect.width / 2) * dpr; const originY = (checkboxRect.top - rect.top + checkboxRect.height / 2) * dpr; const style = getComputedStyle(rowEl); const paletteVars = ['--confetti-1', '--confetti-2', '--confetti-3', '--confetti-4', '--confetti-5', '--confetti-6']; let palette = paletteVars.map(name => style.getPropertyValue(name).trim()).filter(Boolean); if (!palette.length) { palette = ['#2ecc71', '#3498db', '#9b59b6', '#f1c40f', '#e67e22', '#e74c3c']; } const duration = 0.85; const gravity = 900 * dpr; const particleCount = 26; const particles = []; for (let i = 0; i < particleCount; i++) { const angle = (Math.random() * Math.PI / 1.2) - (Math.PI / 2.4); const speed = (260 + Math.random() * 160) * dpr; particles.push({ x: originX, y: originY, vx: Math.cos(angle) * speed, vy: Math.sin(angle) * speed, life: 0, ttl: duration, color: palette[i % palette.length], size: (6 + Math.random() * 6) * dpr, shape: Math.random() > 0.5 ? 'square' : 'circle', rotation: Math.random() * Math.PI * 2, vr: (Math.random() * 4 - 2) }); }
  const state = confettiState.get(rowEl); if (state && state.cancel) { state.cancel(); } let rafId = 0; const start = performance.now(); let prev = start; ctx.clearRect(0, 0, canvas.width, canvas.height); const draw = now => { const dt = (now - prev) / 1000; prev = now; const elapsed = (now - start) / 1000; ctx.clearRect(0, 0, canvas.width, canvas.height); let active = false; for (const p of particles) { p.life = elapsed; const t = Math.min(1, elapsed / p.ttl); if (t >= 1) continue; active = true; p.vy += gravity * dt; p.x += p.vx * dt; p.y += p.vy * dt; const alpha = 1 - t; ctx.save(); ctx.globalAlpha = Math.max(0, alpha); ctx.translate(p.x, p.y); p.rotation += p.vr * dt; ctx.rotate(p.rotation); ctx.fillStyle = p.color.trim() || '#fff'; if (p.shape === 'circle') { ctx.beginPath(); ctx.arc(0, 0, p.size / 2, 0, Math.PI * 2); ctx.fill(); } else { ctx.fillRect(-p.size / 2, -p.size / 2, p.size, p.size); } ctx.restore(); } if (active) { rafId = requestAnimationFrame(draw); } else { ctx.clearRect(0, 0, canvas.width, canvas.height); confettiState.delete(rowEl); } }; rafId = requestAnimationFrame(draw); confettiState.set(rowEl, { cancel() { if (rafId) cancelAnimationFrame(rafId); ctx.clearRect(0, 0, canvas.width, canvas.height); confettiState.delete(rowEl); } }); }

function animateCheckboxBounce(el) { if (!el || isMotionReduced()) return; el.classList.remove('is-bouncing'); void el.offsetWidth; el.classList.add('is-bouncing'); }

export function handleTaskCompletionEffects(taskId, { completed = false, undone = false } = {}) {
  if (undone) { sessionCompletedCount = Math.max(0, sessionCompletedCount - 1); return; }
  if (!completed) return;
  const base = 600 + sessionCompletedCount * 250;
  sessionCompletedCount = Math.min(sessionCompletedCount + 1, Number.MAX_SAFE_INTEGER);
  if (isSoundEnabled()) { try { playTaskCompleteBell(base); } catch {} }
  const rowEl = document.querySelector(`.task[data-id="${taskId}"]`);
  const checkboxEl = rowEl?.querySelector('.task-checkbox');
  if (checkboxEl) { requestAnimationFrame(() => animateCheckboxBounce(checkboxEl)); }
  if (rowEl && checkboxEl) { requestAnimationFrame(() => spawnTaskConfetti(rowEl, checkboxEl)); }
}
