import { MIN_TASK_MINUTES, MAX_TASK_MINUTES, TIME_PRESETS } from './config.js';
import { clampTimeSpentMs, formatDuration } from './utils.js';
import { findTask, tasks, stopTaskTimer, syncTimerLoop, removeActiveTimerState, totalTimeMs } from './tasks-data.js';
import { isServerMode, Store } from './storage.js';
import { queueTaskUpdate, runServerAction, apiRequest } from './api.js';
import { updateTimerDisplays, updateTimeControlsState } from './tasks-render.js';

const _cb = {};
export function registerTimeDialogCallbacks(cbs) { Object.assign(_cb, cbs); }

export function minutesToMs(minutes) { return clampTimeSpentMs(Math.round(minutes || 0) * 60000); }
function msToMinutes(ms) { return Math.round(clampTimeSpentMs(ms) / 60000); }
function isMinutesWithinBounds(minutes) { return Number.isFinite(minutes) && minutes >= MIN_TASK_MINUTES && minutes <= MAX_TASK_MINUTES; }
function normalizeMinutes(value) { const minutes = Math.round(Number(value)); if (!Number.isFinite(minutes)) return null; return isMinutesWithinBounds(minutes) ? minutes : null; }
export function getTaskMinutes(task, now = Date.now()) { return msToMinutes(totalTimeMs(task, now)); }
export function formatPresetLabel(minutes) { if (minutes % 60 === 0 && minutes >= 60) { const hours = minutes / 60; return `+${hours}ч`; } return `+${minutes} мин`; }

const pendingTimeUpdates = new Set();
export function isTimeUpdatePending(taskId) { return pendingTimeUpdates.has(taskId); }
export function setTimeUpdatePending(taskId, value) { if (!taskId) return; const before = pendingTimeUpdates.has(taskId); if (value) { pendingTimeUpdates.add(taskId); } else { pendingTimeUpdates.delete(taskId); } if (before !== value) updateTimeControlsState(taskId); }

function applyTaskTime(task, timeMs, { skipRender = false } = {}) { if (!task) return; task.timeSpent = clampTimeSpentMs(timeMs); task.timerActive = false; task.timerStart = null; removeActiveTimerState(task.id); Store.write(tasks); syncTimerLoop(); updateTimerDisplays(); if (!skipRender) updateTimeControlsState(task.id); }
export function saveTaskTimeMinutes(taskId, newMinutes, { showSuccessToast = false } = {}) { const task = findTask(taskId); if (!task) return Promise.reject(new Error('Задача не найдена')); const normalized = normalizeMinutes(newMinutes); if (normalized === null) return Promise.reject(new Error('Неверное значение времени')); const timeMs = minutesToMs(normalized); if (!isServerMode()) { applyTaskTime(task, timeMs); if (showSuccessToast) _cb.toast(`Время обновлено: ${formatDuration(timeMs)}`); return Promise.resolve(); } return runServerAction(() => apiRequest(`/tasks/${encodeURIComponent(task.id)}`, { method: 'PUT', body: { timeSpent: timeMs } }), { silent: true }).then(() => { applyTaskTime(task, timeMs); if (showSuccessToast) _cb.toast(`Время обновлено: ${formatDuration(timeMs)}`); }); }
export function handleInlinePreset(taskId, delta) { const task = findTask(taskId); if (!task) return; if (task.timerActive || isTimeUpdatePending(task.id)) return; const currentMinutes = getTaskMinutes(task); const nextMinutes = currentMinutes + delta; if (!isMinutesWithinBounds(nextMinutes)) return; setTimeUpdatePending(task.id, true); saveTaskTimeMinutes(task.id, nextMinutes).catch(() => _cb.toast('Не удалось сохранить время. Попробуй ещё раз.')).finally(() => { setTimeUpdatePending(task.id, false); updateTimerDisplays(); }); }

const TimeDialog = { overlay: document.getElementById('timeOverlay'), close: document.getElementById('timeDialogClose'), cancel: document.getElementById('timeDialogCancel'), form: document.getElementById('timeDialogForm'), hours: document.getElementById('timeInputHours'), minutes: document.getElementById('timeInputMinutes'), summary: document.getElementById('timeDialogSummary'), subtitle: document.getElementById('timeDialogSubtitle'), error: document.getElementById('timeDialogError'), save: document.getElementById('timeDialogSave'), presets: document.getElementById('timeDialogPresets') };
let timeDialogTaskId = null;
let timeDialogEditedMinutes = 0;
let timeDialogSaving = false;
let timeDialogDeferredTimerSyncTaskId = null;

export function isTimeDialogOpen() { return !!(TimeDialog.overlay && TimeDialog.overlay.classList.contains('is-open')); }
export function getTimeDialogTaskId() { return timeDialogTaskId; }

function setTimeDialogError(msg) { if (!TimeDialog.error) return; TimeDialog.error.textContent = msg || ''; }
function setTimeDialogInputsFromMinutes(minutes) { const safe = Math.max(0, Math.round(minutes)); const hours = Math.floor(safe / 60); const mins = safe % 60; if (TimeDialog.hours) TimeDialog.hours.value = String(hours); if (TimeDialog.minutes) TimeDialog.minutes.value = String(mins); }
function getTimeDialogState() { if (!TimeDialog.hours || !TimeDialog.minutes) return { valid: false, totalMinutes: 0, hours: 0, minutes: 0, hoursInvalid: true, minutesInvalid: true, rangeInvalid: true }; const rawHours = Number(TimeDialog.hours.value); const rawMinutes = Number(TimeDialog.minutes.value); const hoursInvalid = !Number.isFinite(rawHours) || rawHours < 0; const minutesInvalid = !Number.isFinite(rawMinutes) || rawMinutes < 0 || rawMinutes > 59; const hours = Math.floor(Number.isFinite(rawHours) ? rawHours : 0); const minutes = Math.floor(Number.isFinite(rawMinutes) ? rawMinutes : 0); const totalMinutes = hours * 60 + minutes; const rangeInvalid = totalMinutes < MIN_TASK_MINUTES || totalMinutes > MAX_TASK_MINUTES; const valid = !hoursInvalid && !minutesInvalid && !rangeInvalid; return { valid, totalMinutes, hours, minutes, hoursInvalid, minutesInvalid, rangeInvalid }; }
function updateTimeDialogUI({ showValidationError = false, preserveError = false } = {}) { const state = getTimeDialogState(); timeDialogEditedMinutes = state.totalMinutes; if (TimeDialog.summary) { const displayMinutes = Math.min(MAX_TASK_MINUTES, Math.max(MIN_TASK_MINUTES, state.totalMinutes)); TimeDialog.summary.textContent = formatDuration(minutesToMs(displayMinutes)); } if (TimeDialog.save) TimeDialog.save.disabled = !state.valid || timeDialogSaving; if (TimeDialog.hours) TimeDialog.hours.classList.toggle('is-invalid', state.hoursInvalid); if (TimeDialog.minutes) TimeDialog.minutes.classList.toggle('is-invalid', state.minutesInvalid || state.rangeInvalid); if (!preserveError) { if (!state.valid || showValidationError) { setTimeDialogError('Неверное значение времени'); } else if (!timeDialogSaving) { setTimeDialogError(''); } } return state; }
function applyTimeDialogPreset(delta) { const next = timeDialogEditedMinutes + delta; setTimeDialogInputsFromMinutes(Math.max(0, next)); timeDialogEditedMinutes = next; updateTimeDialogUI({ showValidationError: next < MIN_TASK_MINUTES || next > MAX_TASK_MINUTES }); }
export function openTimeEditDialog(taskId) { const task = findTask(taskId); if (!task || !TimeDialog.overlay) return; if (task.timerActive) { stopTaskTimer(task, { skipServer: true }); timeDialogDeferredTimerSyncTaskId = task.id; syncTimerLoop(); } else { timeDialogDeferredTimerSyncTaskId = null; } timeDialogTaskId = taskId; const currentMinutes = getTaskMinutes(task); timeDialogEditedMinutes = currentMinutes; if (TimeDialog.subtitle) TimeDialog.subtitle.textContent = currentMinutes ? `Текущее значение: ${formatDuration(minutesToMs(currentMinutes))}` : 'Текущее значение: 0 мин'; setTimeDialogInputsFromMinutes(currentMinutes); setTimeDialogError(''); timeDialogSaving = false; updateTimeDialogUI(); TimeDialog.overlay.classList.add('is-open'); TimeDialog.overlay.setAttribute('aria-hidden', 'false'); document.body.classList.add('time-dialog-open'); updateTimeControlsState(taskId); const focusTarget = TimeDialog.minutes || TimeDialog.hours; setTimeout(() => { if (!focusTarget) return; try { focusTarget.focus({ preventScroll: true }); } catch { focusTarget.focus(); } }, 60); }
export function closeTimeDialog({ syncDeferred = true } = {}) { if (!TimeDialog.overlay) return; const taskId = timeDialogTaskId; const shouldSyncDeferred = syncDeferred && timeDialogDeferredTimerSyncTaskId && taskId === timeDialogDeferredTimerSyncTaskId; timeDialogTaskId = null; timeDialogSaving = false; timeDialogEditedMinutes = 0; TimeDialog.overlay.classList.remove('is-open'); TimeDialog.overlay.setAttribute('aria-hidden', 'true'); document.body.classList.remove('time-dialog-open'); setTimeDialogError(''); if (TimeDialog.save) TimeDialog.save.disabled = false; if (shouldSyncDeferred) { const task = findTask(taskId); if (task && isServerMode()) { queueTaskUpdate(task.id, { timeSpent: task.timeSpent }); } } timeDialogDeferredTimerSyncTaskId = null; updateTimeControlsState(taskId); }
function submitTimeDialog() { if (!timeDialogTaskId || timeDialogSaving) return; const task = findTask(timeDialogTaskId); if (!task) { closeTimeDialog(); return; } const state = updateTimeDialogUI({ showValidationError: true }); if (!state.valid) { return; } timeDialogSaving = true; updateTimeDialogUI({ preserveError: true }); setTimeDialogError(''); setTimeUpdatePending(task.id, true); saveTaskTimeMinutes(task.id, state.totalMinutes, { showSuccessToast: true }).then(() => { timeDialogDeferredTimerSyncTaskId = null; closeTimeDialog({ syncDeferred: false }); }).catch(() => { setTimeDialogError('Не удалось сохранить. Проверь соединение и попробуй ещё раз.'); }).finally(() => { timeDialogSaving = false; setTimeUpdatePending(task.id, false); updateTimeDialogUI({ preserveError: true }); updateTimerDisplays(); }); }
function initTimeDialogPresets() { if (!TimeDialog.presets) return; TimeDialog.presets.innerHTML = ''; for (const delta of TIME_PRESETS) { const btn = document.createElement('button'); btn.type = 'button'; btn.className = 'time-preset-btn'; btn.textContent = formatPresetLabel(delta); btn.title = `Добавить ${formatDuration(minutesToMs(delta))}`; btn.onclick = e => { e.preventDefault(); applyTimeDialogPreset(delta); }; TimeDialog.presets.appendChild(btn); } }

// Event listeners
TimeDialog.overlay && TimeDialog.overlay.addEventListener('click', e => { if (e.target === TimeDialog.overlay) closeTimeDialog(); });
TimeDialog.close && TimeDialog.close.addEventListener('click', () => closeTimeDialog());
TimeDialog.cancel && TimeDialog.cancel.addEventListener('click', () => closeTimeDialog());
TimeDialog.form && TimeDialog.form.addEventListener('submit', e => { e.preventDefault(); submitTimeDialog(); });
for (const input of [TimeDialog.hours, TimeDialog.minutes]) { if (!input) continue; input.addEventListener('input', () => updateTimeDialogUI()); input.addEventListener('blur', () => { const state = getTimeDialogState(); if (state.valid) setTimeDialogInputsFromMinutes(state.totalMinutes); updateTimeDialogUI({ showValidationError: true }); }); }
initTimeDialogPresets();
