name: Promote STG → PROD (tasks)

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: "Напиши YES для промоута /var/www/tasks-stg → /var/www/tasks-prod"
        required: true
        default: "YES"

jobs:
  promote:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.confirm == 'YES' }}
    env:
      SSH_HOST: ${{ secrets.DEPLOY_HOST }}
      SSH_USER: ${{ secrets.DEPLOY_USER }}
      SSH_KEY:  ${{ secrets.SSH_KEY }}
      PATH_PROD: ${{ secrets.DEPLOY_PATH_PROD }}
      PATH_STG:  ${{ secrets.DEPLOY_PATH_STG }}

    steps:
      - name: Prepare SSH key
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_KEY" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          printf "Host ${SSH_HOST}\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

      - name: Promote files atomically (rsync STG → PROD on server)
        run: |
          ssh -i ~/.ssh/id_ed25519 ${SSH_USER}@${SSH_HOST} "
            set -e
            tmp_dir=\$(mktemp -d)
            rsync -az --delete ${PATH_STG}/ \${tmp_dir}/
            rsync -az --delete \${tmp_dir}/ ${PATH_PROD}/
            rm -rf \${tmp_dir}
            find ${PATH_PROD} -maxdepth 1 -name index.html -exec touch {} +
          "
